name = "Feynman"
uuid = "d671e7a6-f492-4ceb-b56e-12d48ab28268"
authors = ["Dushan Priyasad", "Janko Boehm"]
version = "1.0.0-DEV"

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
