name: Documenter
on:
  push:
    branches:
      - main
      - dev_new
    tags: ['*']
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '^1.5'
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      # Run Singular with the full path to run_Examples.sing
      - name: Run Singular with full path
        run: |
          echo "Running Singular with path to docs/run_Examples.sing"
          Singular $(pwd)/docs/run_Examples.sing 
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --color=yes --project=docs/ docs/make.jl
